### ISSUE TITLE
Performance do Patch para Presenças (Attendance)

### ISSUE THREAD

**Issue by Lucasark** [Lucasark/tcc-resource-server#33]
Foi realizado uma primeira implementação utilizando o recurso nativo do mongo de remover (#32 ), sendo assim:

Antes:

- Buscava a frequencia pelo ID;
- Operar um for para achar a presença;
- Alterava o presença com o status informado;
- Salvar a frequencia alterada;

Depois:

- Remove a presença (independente do status) -> Operar [$PULL ](https://www.mongodb.com/docs/manual/reference/operator/update/pull/)
- Inclui a presença com o status informado -> Operar [$addToSet](https://www.mongodb.com/docs/manual/reference/operator/update/addToSet/)

**Comment by Lucasark** [comment]
@jsimonassi aguardo o feedback desta melhoria, lembrando que pode evoluir para um PATCH de Lista de "presenças" caso tivemos um bom resultado

**Comment by Lucasark** [comment]
Test de carga em Deploy:

<img width="1724" alt="image" src="https://github.com/Lucasark/tcc-resource-server/assets/31750882/0913b18c-e837-47b5-9515-2864cba7f49e">

**Comment by Lucasark** [comment]
Foi aberto uma otimização a nivel de frequencia #42, sendo assim, por enquanto essa validação não será realizada

**Comment by Lucasark** [comment]
Validação foi retomada com a finalização da #42

**Comment by jsimonassi** [comment]
O teste foi realizado e o consumo foi validado pelo frontend. O endpoint está funcionando bem e de acordo com o esperado.
