### ISSUE TITLE
Endpoints da Marcação de Presença para Rotina Estatica

### ISSUE THREAD

**Issue by Lucasark** [Lucasark/tcc-resource-server#37]
Serão 2 endpoints:

- START 
- STOP

Seguiram com as mesmas regras que foram feitas para o WS

**Comment by Lucasark** [comment]
O endpoint mudou para ser semelhante ao de WS, sendo assim, necessario apenas 1 endpoint o que muda é commando dados no Body

**Comment by Lucasark** [comment]
@jsimonassi Testar feature,
Em testes Locais foram com sucesso, porém tem que validar em conjunto com o WS

**Comment by jsimonassi** [comment]
Endpoint validado! 
Está funcionando como esperado.
