### ISSUE TITLE
Batch de Incluir de alunos

### ISSUE THREAD

**Issue by Lucasark** [Lucasark/tcc-resource-server#39]
Feature para incluir alunos utlizando recurso assicrono, assim o consumidor de API não precisa esperar pela criação dos alunos, oque pro sua vez é um pouco custoso

**Comment by Lucasark** [comment]
Está será a arquitetura inicial
![untitled](https://github.com/Lucasark/tcc-resource-server/assets/31750882/4efbdd6a-fc65-41e7-aaff-c4d8b8011934)
Ela foi feita para ser generica, atender qualquer necessidade de Batch; hoje tem a necessidade de criar usuarios dentro de um curso, mas caso precisa de outra necessidade será possivel

Endpoints:

/add-members -> Terá como uso igual é o do antigo members-batch, porém utilizando o recurso assincrono; e irá iniciar uma Batch do tipo "MEMBERS";

/?target={type} -> Buscar todos Batchs criados, pode ser filtrado pelo tipo de Batch (Hoje, apenas MEMBERS);

/{id}/viewed/ -> Marcar Batch como visualizado pelo Consumidor;

/{id} -> Buscar informações sobre aquele Batch;

/missed?target={type} -> Buscar todos os Batch que ainda não foram marcadas como visualizados pelo Consumidor, pode ser filtrado pelo tipo de Batch (Hoje, apenas MEMBERS);

**Comment by Lucasark** [comment]
@jsimonassi recurso implementado, pronto para testar estrutura a nível de front-end

**Comment by jsimonassi** [comment]
Implementado e validado no frontend! Funcionando como esperado.

Um detalhe que percebi é que se fizer um get por id do batch enquanto ele não é finalizado, nenhum aluno é retornado. Faz sentido que ele retorne os alunos já adicionados até um momento. Isso não é um problema pois depois que finaliza ele retorna certinho, mas estou comentando aqui pra que fique registrado.

Mesmo com esse detalhe, estou fechando a task, uma vez que os requisitos iniciais foram atendidos.
