### ISSUE TITLE
Endpoint /users não retorna o atributo "nome"

### ISSUE THREAD

**Issue by jsimonassi** [Lucasark/tcc-resource-server#7]
O endpoint: `/users` retorna um objeto com esse modelo:

```
{
"alias": null, 
"email": "joaovictorsimonassifarias@gmail.com", 
"registration": null
}
```

Nesse caso, é esperado que o alias e o registration sejam nulos, uma vez que o usuário foi cadastrado pelo app mobile e não enviou essas informações (Só serão enviadas quando o professor cadastrar o aluno manualmente ou via planilha).

Porém, o atributo "name" não é retornado. 
Verifiquei no banco e ele está sendo salvo como esperado.

**Comment by Lucasark** [comment]
Foi realizado um expurgo de banco pois estava defasado com os novos alinhamentos;
Alem disso, aproveitando o expurgo, foram incluidos as melhorias de metricas e otimização de documento para MongoDB, dentro do banco.

Talvez seja necessário validar alguns fluxos como cadastro de um curso e alunos dentro de curso.

**Comment by Lucasark** [comment]
Evidencia: 

<img width="1299" alt="image" src="https://github.com/Lucasark/tcc-resource-server/assets/31750882/4e7862c3-1260-4aa3-a24f-268c10c27b1a">

@jsimonassi fazer um novo cadastro.

**Comment by jsimonassi** [comment]
Fluxo validado! Funcionando como esperado. Obrigado! 👍🏻 💯
